
package ca.bcit.comp4656.employee.operations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeOperationsService", targetNamespace = "http://operations.employee.comp4656.bcit.ca/", wsdlLocation = "http://localhost:8080/A00818459ws/EmployeeOperations?wsdl")
public class EmployeeOperationsService
    extends Service
{

    private final static URL EMPLOYEEOPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEOPERATIONSSERVICE_EXCEPTION;
    private final static QName EMPLOYEEOPERATIONSSERVICE_QNAME = new QName("http://operations.employee.comp4656.bcit.ca/", "EmployeeOperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/A00818459ws/EmployeeOperations?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEOPERATIONSSERVICE_WSDL_LOCATION = url;
        EMPLOYEEOPERATIONSSERVICE_EXCEPTION = e;
    }

    public EmployeeOperationsService() {
        super(__getWsdlLocation(), EMPLOYEEOPERATIONSSERVICE_QNAME);
    }

    public EmployeeOperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEOPERATIONSSERVICE_QNAME, features);
    }

    public EmployeeOperationsService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEOPERATIONSSERVICE_QNAME);
    }

    public EmployeeOperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEOPERATIONSSERVICE_QNAME, features);
    }

    public EmployeeOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeOperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "EmployeeOperationsPort")
    public EmployeeServicePort getEmployeeOperationsPort() {
        return super.getPort(new QName("http://operations.employee.comp4656.bcit.ca/", "EmployeeOperationsPort"), EmployeeServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns EmployeeServicePort
     */
    @WebEndpoint(name = "EmployeeOperationsPort")
    public EmployeeServicePort getEmployeeOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://operations.employee.comp4656.bcit.ca/", "EmployeeOperationsPort"), EmployeeServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEOPERATIONSSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEOPERATIONSSERVICE_EXCEPTION;
        }
        return EMPLOYEEOPERATIONSSERVICE_WSDL_LOCATION;
    }

}
